#Generated Form Function
function GenerateForm {
########################################################################
# Generated By: klajosw@gmail.com
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$form1 = New-Object System.Windows.Forms.Form
$B_uj = New-Object System.Windows.Forms.Button
$L_panel = New-Object System.Windows.Forms.Label
$L_kiir = New-Object System.Windows.Forms.Label
$B_Kilep = New-Object System.Windows.Forms.Button
$B_gen = New-Object System.Windows.Forms.Button
$B_azon = New-Object System.Windows.Forms.Button
$T_samacount = New-Object System.Windows.Forms.TextBox
$T_incidens = New-Object System.Windows.Forms.TextBox
$L_sam2 = New-Object System.Windows.Forms.Label
$L_incidens = New-Object System.Windows.Forms.Label
$L_sam = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects
$check = 0
#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$Generalas= 
{
	if ($T_samacount.text -eq ""){
		$L_kiir.text ="A file generálásához kell samacount nevet megadni!!!"
	}
	elseif ($T_incidens.text -eq ""){
		$L_kiir.text ="A file generálásához kell incidens számot megadni!!!"
	}
	elseif($check -eq 0){
		$L_kiir.text ="A file generálása elött azonosítás szükséges!!!"
	}
	elseif($T_samacount.text -ne $a.SamAccountName){
		$L_kiir.text ="A SamAccountName megváltozott!!! File generálás elõtt Azonosítás szükséges!!!"
	}
	else{
		#bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb---- A FILE elérési útvonala ---bbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbbb
		$path = "\\k-ub1\User_backups\" + $T_incidens.text
		$name = $a.SamAccountName + ".kfkirestore"
		if((Test-Path $path) -ceq $true){
			if((Test-Path "$path\*.kfkirestore") -ceq $true){
				$L_kiir.text ="Az adott könyvtárban már létezik  `".kfkirestore`"  kiterjesztésû file. `nKérem ellenõrizze, hogy a megfelelõ szerepel-e ott!`n   A könyvtár helye: `n      $path"
			}else{
				new-item -Path $path -Name $name -type file
				$L_kiir.text ="A  $name  file generálása megtörtént a következõ helyre: `n   $path"
			}
		}else{
			$L_kiir.text ="A `"" + $T_incidens.text + "`" nevû könyvtár nem létezik. Kérem ellenõrizze, hogy a megadott Incidens szám helyes e!"
		}
	}
}

$Azonositas= 
{
	$check = 0
	if ($T_samacount.text -cne ""){
		$a = Get-QADUser $T_samacount.text -ErrorAction SilentlyContinue
		$c= get-qaduser $a.manager
		$felettes = $c.DisplayName
		if ($a -cne $null){
			$L_kiir.text = "A megadott személy adatai: " + "`n" + "   Név: " + $a.DisplayName + "`n   Osztály: " + $a.Department + "`n   Felettes: " + $felettes
			$check = 1
		}else {
			$L_kiir.text = "A keresett személy nem található, vagy hiba van a megadott névben!"
		}
	}else{
		$L_kiir.text = "A kereséshez szükséges nevet megadni!"
	}
}

$Uj_kereses= 
{
	$T_incidens.text = ""
	$T_samacount.text = ""
	$L_kiir.text = ""
	$a = $null
	$check = 0
}

$kilepes= 
{
	$form1.close()
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$form1.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$form1.Text = '".kfkirestore" file generating'
$form1.Name = 'form1'
$form1.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 566
$System_Drawing_Size.Height = 470
$form1.ClientSize = $System_Drawing_Size
$form1.FormBorderStyle = 2
$form1.add_Load($handler_form1_Load)

$L_panel.TabIndex = 9
$L_panel.TextAlign = 16
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 140
$System_Drawing_Size.Height = 23
$L_panel.Size = $System_Drawing_Size
$L_panel.Text = 'A keresett személy adatai:'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 163
$L_panel.Location = $System_Drawing_Point
$L_panel.DataBindings.DefaultDataSourceUpdateMode = 0
$L_panel.Name = 'L_panel'

$form1.Controls.Add($L_panel)

$L_kiir.TabIndex = 10
$L_kiir.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 504
$System_Drawing_Size.Height = 209
$L_kiir.Size = $System_Drawing_Size
$L_kiir.BorderStyle = 1

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 186
$L_kiir.Location = $System_Drawing_Point
$L_kiir.DataBindings.DefaultDataSourceUpdateMode = 0
$L_kiir.Name = 'L_kiir'
$L_kiir.text = ""

$form1.Controls.Add($L_kiir)

$B_Kilep.TabIndex = 7
$B_Kilep.Name = 'B_Kilep'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$B_Kilep.Size = $System_Drawing_Size
$B_Kilep.UseVisualStyleBackColor = $True

$B_Kilep.Text = 'Kilépés'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 408
$System_Drawing_Point.Y = 415
$B_Kilep.Location = $System_Drawing_Point
$B_Kilep.DataBindings.DefaultDataSourceUpdateMode = 0
$B_Kilep.add_Click($kilepes)

$form1.Controls.Add($B_Kilep)

$B_gen.TabIndex = 6
$B_gen.Name = 'B_gen'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$B_gen.Size = $System_Drawing_Size
$B_gen.UseVisualStyleBackColor = $True

$B_gen.Text = 'File Generálás'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 42
$System_Drawing_Point.Y = 415
$B_gen.Location = $System_Drawing_Point
$B_gen.DataBindings.DefaultDataSourceUpdateMode = 0
$B_gen.add_Click($Generalas)

$form1.Controls.Add($B_gen)

$B_azon.TabIndex = 5
$B_azon.Name = 'B_azon'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$B_azon.Size = $System_Drawing_Size
$B_azon.UseVisualStyleBackColor = $True

$B_azon.Text = 'Azonosítás'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 408
$System_Drawing_Point.Y = 116
$B_azon.Location = $System_Drawing_Point
$B_azon.DataBindings.DefaultDataSourceUpdateMode = 0
$B_azon.add_Click($Azonositas)

$form1.Controls.Add($B_azon)


$B_uj.TabIndex = 11
$B_uj.Name = 'B_uj'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$B_uj.Size = $System_Drawing_Size
$B_uj.UseVisualStyleBackColor = $True

$B_uj.Text = 'Új keresés'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 408
$System_Drawing_Point.Y = 85
$B_uj.Location = $System_Drawing_Point
$B_uj.DataBindings.DefaultDataSourceUpdateMode = 0
$B_uj.add_Click($Uj_kereses)

$form1.Controls.Add($B_uj)


$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 164
$System_Drawing_Size.Height = 20
$T_samacount.Size = $System_Drawing_Size
$T_samacount.DataBindings.DefaultDataSourceUpdateMode = 0
$T_samacount.Name = 'T_samacount'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 119
$T_samacount.Location = $System_Drawing_Point
$T_samacount.TabIndex = 4

$form1.Controls.Add($T_samacount)

$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 164
$System_Drawing_Size.Height = 20
$T_incidens.Size = $System_Drawing_Size
$T_incidens.DataBindings.DefaultDataSourceUpdateMode = 0
$T_incidens.Name = 'T_incidens'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 172
$System_Drawing_Point.Y = 88
$T_incidens.Location = $System_Drawing_Point
$T_incidens.TabIndex = 3

$form1.Controls.Add($T_incidens)

$L_sam2.TabIndex = 2
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 105
$System_Drawing_Size.Height = 25
$L_sam2.Size = $System_Drawing_Size
$L_sam2.Text = 'SamAccountName:'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 51
$System_Drawing_Point.Y = 122
$L_sam2.Location = $System_Drawing_Point
$L_sam2.DataBindings.DefaultDataSourceUpdateMode = 0
$L_sam2.Name = 'L_sam2'

$form1.Controls.Add($L_sam2)

$L_incidens.TabIndex = 1
$L_incidens.TextAlign = 16
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 100
$System_Drawing_Size.Height = 23
$L_incidens.Size = $System_Drawing_Size
$L_incidens.Text = 'Incidens szám:'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 51
$System_Drawing_Point.Y = 86
$L_incidens.Location = $System_Drawing_Point
$L_incidens.DataBindings.DefaultDataSourceUpdateMode = 0
$L_incidens.Name = 'L_incidens'

$form1.Controls.Add($L_incidens)

$L_sam.TabIndex = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Width = 417
$System_Drawing_Size.Height = 35
$L_sam.Size = $System_Drawing_Size
$L_sam.Text = 'A kereséshez kérem adja meg az incidens számot, és a személy SamAccount nevét:  (pl.: nemeth2laszlo, sneff.gabor, olahzoltan)'

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 27
$System_Drawing_Point.Y = 33
$L_sam.Location = $System_Drawing_Point
$L_sam.DataBindings.DefaultDataSourceUpdateMode = 0
$L_sam.Name = 'L_sam'

$form1.Controls.Add($L_sam)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $form1.WindowState
#Init the OnLoad event to correct the initial state of the form
$form1.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$form1.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
