#Generated Form Function
function GenerateForm {
########################################################################
# Code Generated By: SAPIEN Technologies PrimalForms (Community Edition) v1.0.3.0
# Generated On: 2009.05.26. 13:44
# Generated By: kokaipeter
########################################################################

#region Import the Assemblies
[reflection.assembly]::loadwithpartialname("System.Drawing") | Out-Null
[reflection.assembly]::loadwithpartialname("System.Windows.Forms") | Out-Null
#endregion

#region Generated Form Objects
$Urlap = New-Object System.Windows.Forms.Form
$Subject = New-Object System.Windows.Forms.TextBox
$label2 = New-Object System.Windows.Forms.Label
$Cimke = New-Object System.Windows.Forms.Label
$DateTo = New-Object System.Windows.Forms.DateTimePicker
$DateFrom = New-Object System.Windows.Forms.DateTimePicker
$B_Exit = New-Object System.Windows.Forms.Button
$B_Keres = New-Object System.Windows.Forms.Button
$ChkDateTo = New-Object System.Windows.Forms.CheckBox
$ChckDateFrom = New-Object System.Windows.Forms.CheckBox
$Sender = New-Object System.Windows.Forms.TextBox
$ChkSender = New-Object System.Windows.Forms.CheckBox
$Recipient = New-Object System.Windows.Forms.TextBox
$ChkSubjekt = New-Object System.Windows.Forms.CheckBox
$ChckRecipient = New-Object System.Windows.Forms.CheckBox
$Result = New-Object System.Windows.Forms.Label
$InitialFormWindowState = New-Object System.Windows.Forms.FormWindowState
#endregion Generated Form Objects

#----------------------------------------------
#Generated Event Script Blocks
#----------------------------------------------
#Provide Custom Code for events specified in PrimalForms.
$DateFromChange= 
{
	if($ChckDateFrom.checked)
	{	
		$DateFrom.Enabled = $True
	}
	else{ 
		$DateFrom.Enabled = $False
	}
}

$DateToChange= 
{
	if($ChkDateTo.checked)
	{	
		$DateTo.Enabled = $True
	}
	else{ 
		$DateTo.Enabled = $False
	}
}

$SenderChange= 
{
	if($ChkSender.checked)
	{	
		$Sender.Enabled = $True
	}
	else{ 
		$Sender.Enabled = $False
	}
}

$vegrehajt= 
{

}

$SbubjectChange= 
{
	if($ChkSubjekt.checked)
	{	
		$Subject.Enabled = $True
	}
	else{ 
		$Subject.Enabled = $False
	}
}

$RecipChange= 
{
	if($ChckRecipient.checked)
	{	
		$Recipient.Enabled = $True
	}
	else{ 
		$Recipient.Enabled = $False
	}
}

$ExitForm= 
{
	$Urlap.Close()
}

$B_Keres_OnClick= 
{
	$command = ''
	if ($ChckRecipient.checked){
		$command = $command + '-Recipients ' + $Recipient.text + ' '
	}
	if ($ChkSender.checked){
		 $command = $command + '-Sender ' + $Sender.Text + ' '
	}
	if ($ChkSubjekt.checked){
		 $command = $command + '-MessageSubject ' + $Subject.Text + ' '
	}
	if ($ChckDateFrom.checked){
		 $command = $command + '-Start ' + $DateFrom.Text + ' '
	}
	if ($ChkDateTo.checked){
		 $command = $command + '-End ' + $DateTo.Text + ' '
	}	
	#$Recipient1 = '"' + $Recipient.text + '"'
	#get-messagetrackinglog -Recipients:kokai.peter@kfkizrt.hu -Sender "olah.zoltan@kfkizrt.hu" -Server "k-mail3hc1"	-MessageSubject "tesztemail234" -Start "2009 05 21 12:39:00" -End "2009 05 21 12:50:00" | fl
	#$Result.Text = 'get-messagetrackinglog -Recipients:' + $Sender.Text + '-Sender ' + $Recipient.Text + ' -Server k-mail3hc1 -MessageSubject " + $Subject.Text + " -Start 2009 05 21 12:39:00 -End 2009 05 21 12:50:00 | fl'
	#$Result2 = get-messagetrackinglog -Recipients $Recipient.text -Server "k-mail3hc1" | fl
	#$Result2 = get-messagetrackinglog $command -Server "k-mail3hc1" | fl
	$Result.Text ='A végrehajtott parancs: get-messagetrackinglog ' + $command
	
}

$OnLoadForm_StateCorrection=
{#Correct the initial state of the form to prevent the .Net maximized form issue
	$Urlap.WindowState = $InitialFormWindowState
}

#----------------------------------------------
#region Generated Form Code
$Urlap.Font = New-Object System.Drawing.Font("Microsoft Sans Serif",9,0,3,0)
$Urlap.Text = 'Mail Tracker'
$Urlap.Name = 'Urlap'
$Urlap.DataBindings.DefaultDataSourceUpdateMode = 0
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 505
$System_Drawing_Size.Width = 747
$Urlap.ClientSize = $System_Drawing_Size

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 254
$Subject.Location = $System_Drawing_Point
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 157
$Subject.Size = $System_Drawing_Size
$Subject.DataBindings.DefaultDataSourceUpdateMode = 0
$Subject.Name = 'Subject'
$Subject.Enabled = $False
$Subject.TabIndex = 20

$Urlap.Controls.Add($Subject)

$label2.TabIndex = 19
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 53
$System_Drawing_Size.Width = 213
$label2.Size = $System_Drawing_Size
$label2.Name = 'label2'
$label2.Text = 'Kerem adja meg a visszakereseshez szukseges adatokat, beallitasokat, a megfelelo opciok kivalasztasaval!'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 56
$label2.Location = $System_Drawing_Point

$label2.DataBindings.DefaultDataSourceUpdateMode = 0

$Urlap.Controls.Add($label2)

$Cimke.TabIndex = 18
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 137
$Cimke.Size = $System_Drawing_Size
$Cimke.TextAlign = 16
$Cimke.Name = 'Cimke'
$Cimke.Text = 'A keresés eredménye:'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 395
$System_Drawing_Point.Y = 40
$Cimke.Location = $System_Drawing_Point

$Cimke.ImageAlign = 2
$Cimke.DataBindings.DefaultDataSourceUpdateMode = 0

$Urlap.Controls.Add($Cimke)

$DateTo.Name = 'DateTo'
$DateTo.Enabled = $False
$DateTo.DataBindings.DefaultDataSourceUpdateMode = 0
$DateTo.Value = '2009.05.06. 0:00:00'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 157
$DateTo.Size = $System_Drawing_Size
$DateTo.TabIndex = 17
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 339
$DateTo.Location = $System_Drawing_Point
$DateTo.Format = 8
$DateTo.CustomFormat = 'yyyy.MM.dd HH:mm'

$Urlap.Controls.Add($DateTo)

$DateFrom.Name = 'DateFrom'
$DateFrom.Enabled = $False
$DateFrom.DataBindings.DefaultDataSourceUpdateMode = 0
$DateFrom.Value = '2009.05.06. 0:00:00'
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 157
$DateFrom.Size = $System_Drawing_Size
$DateFrom.TabIndex = 16
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 299
$DateFrom.Location = $System_Drawing_Point
$DateFrom.Format = 8
$DateFrom.CustomFormat = 'yyyy.MM.dd HH:mm'

$Urlap.Controls.Add($DateFrom)

$B_Exit.TabIndex = 15
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$B_Exit.Size = $System_Drawing_Size
$B_Exit.Name = 'B_Exit'
$B_Exit.UseVisualStyleBackColor = $True

$B_Exit.Text = 'Kilep'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 285
$System_Drawing_Point.Y = 421
$B_Exit.Location = $System_Drawing_Point

$B_Exit.DataBindings.DefaultDataSourceUpdateMode = 0
$B_Exit.add_Click($ExitForm)

$Urlap.Controls.Add($B_Exit)

$B_Keres.TabIndex = 14
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 23
$System_Drawing_Size.Width = 75
$B_Keres.Size = $System_Drawing_Size
$B_Keres.Name = 'B_Keres'
$B_Keres.UseVisualStyleBackColor = $True

$B_Keres.Text = 'Keres'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 421
$B_Keres.Location = $System_Drawing_Point

$B_Keres.DataBindings.DefaultDataSourceUpdateMode = 0
$B_Keres.add_Click($B_Keres_OnClick)
$B_Keres.add_MouseClick($vegrehajt)

$Urlap.Controls.Add($B_Keres)

$ChkDateTo.TabIndex = 11
$ChkDateTo.CheckAlign = 64
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ChkDateTo.Size = $System_Drawing_Size
$ChkDateTo.Name = 'ChkDateTo'
$ChkDateTo.UseVisualStyleBackColor = $True

$ChkDateTo.Text = 'DateTo'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 339
$ChkDateTo.Location = $System_Drawing_Point

$ChkDateTo.DataBindings.DefaultDataSourceUpdateMode = 0
$ChkDateTo.add_Click($DateToChange)

$Urlap.Controls.Add($ChkDateTo)

$ChckDateFrom.TabIndex = 10
$ChckDateFrom.CheckAlign = 64
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ChckDateFrom.Size = $System_Drawing_Size
$ChckDateFrom.Name = 'ChckDateFrom'
$ChckDateFrom.UseVisualStyleBackColor = $True

$ChckDateFrom.Text = 'DateFrom'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 299
$ChckDateFrom.Location = $System_Drawing_Point

$ChckDateFrom.DataBindings.DefaultDataSourceUpdateMode = 0
$ChckDateFrom.add_Click($DateFromChange)

$Urlap.Controls.Add($ChckDateFrom)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 170
$Sender.Location = $System_Drawing_Point
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 157
$Sender.Size = $System_Drawing_Size
$Sender.DataBindings.DefaultDataSourceUpdateMode = 0
$Sender.Name = 'Sender'
#$Sender.Text = 'alapvalue'
$Sender.Enabled = $False
$Sender.TabIndex = 8

$Urlap.Controls.Add($Sender)

$ChkSender.TabIndex = 7
$ChkSender.CheckState = 1
$ChkSender.CheckAlign = 64
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ChkSender.Size = $System_Drawing_Size
$ChkSender.Name = 'ChkSender'
$ChkSender.UseVisualStyleBackColor = $True

$ChkSender.Text = 'Sender'
$ChkSender.Checked = $False
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 170
$ChkSender.Location = $System_Drawing_Point

$ChkSender.DataBindings.DefaultDataSourceUpdateMode = 0
$ChkSender.add_Click($SenderChange)

$Urlap.Controls.Add($ChkSender)

$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 173
$System_Drawing_Point.Y = 211
$Recipient.Location = $System_Drawing_Point
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 21
$System_Drawing_Size.Width = 157
$Recipient.Size = $System_Drawing_Size
$Recipient.DataBindings.DefaultDataSourceUpdateMode = 0
$Recipient.Name = 'Recipient'
$Recipient.Enabled = $False
$Recipient.TabIndex = 5

$Urlap.Controls.Add($Recipient)

$ChkSubjekt.TabIndex = 4
$ChkSubjekt.CheckAlign = 64
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ChkSubjekt.Size = $System_Drawing_Size
$ChkSubjekt.Name = 'ChkSubjekt'
$ChkSubjekt.UseVisualStyleBackColor = $True

$ChkSubjekt.Text = 'Subject'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 254
$ChkSubjekt.Location = $System_Drawing_Point

$ChkSubjekt.DataBindings.DefaultDataSourceUpdateMode = 0
$ChkSubjekt.add_Click($SbubjectChange)

$Urlap.Controls.Add($ChkSubjekt)

$ChckRecipient.TabIndex = 3
$ChckRecipient.CheckAlign = 64
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 24
$System_Drawing_Size.Width = 104
$ChckRecipient.Size = $System_Drawing_Size
$ChckRecipient.Name = 'ChckRecipient'
$ChckRecipient.UseVisualStyleBackColor = $True

$ChckRecipient.Text = 'Recipient'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 41
$System_Drawing_Point.Y = 211
$ChckRecipient.Location = $System_Drawing_Point

$ChckRecipient.DataBindings.DefaultDataSourceUpdateMode = 0
$ChckRecipient.add_Click($RecipChange)

$Urlap.Controls.Add($ChckRecipient)

$Result.BorderStyle = 1
$Result.TabIndex = 22
$Result.BackColor = [System.Drawing.Color]::FromArgb(255,255,255,255)
$System_Drawing_Size = New-Object System.Drawing.Size
$System_Drawing_Size.Height = 393
$System_Drawing_Size.Width = 330
$Result.Size = $System_Drawing_Size
$Result.Name = 'Result'
$Result.Text = 'Eredmeny:'
$System_Drawing_Point = New-Object System.Drawing.Point
$System_Drawing_Point.X = 395
$System_Drawing_Point.Y = 63
$Result.Location = $System_Drawing_Point

$Result.DataBindings.DefaultDataSourceUpdateMode = 0

$Urlap.Controls.Add($Result)

#endregion Generated Form Code

#Save the initial state of the form
$InitialFormWindowState = $Urlap.WindowState
#Init the OnLoad event to correct the initial state of the form
$Urlap.add_Load($OnLoadForm_StateCorrection)
#Show the Form
$Urlap.ShowDialog()| Out-Null

} #End Function

#Call the Function
GenerateForm
